name: Continuos Integration

on: pull_request

jobs: 
  continous-integration:
    runs-on: ubuntu-lastest
    
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 21.
      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test